#!/bin/bash
#kuni 10ni paarisarvude summa arvutamine
summa=0

for (( arv=1; arv<11; arv++ ))
do
jaak=$(($arv % 2))
if [ $jaak -eq 0 ]; then 

summa=$(($summa + $arv))

echo $summa
fi
done

echo "arvude 1 kuni 11 paarisarvude summa on: $summa"
