#!/bin/bash

#suvaliselst sisestatud arvu numbrite summa arvutamine

summa=0
echo -n "Sisesta suvaline täisarv: "
read arv
n=$arv

while [ $arv -ne 0 ]
do
jaak=$(($arv % 10))
summa=$(($summa + $jaak))
arv=$(($arv / 10))

#väljastab selgitava teksti
done
echo "Arvu $n numbrite summa on $summa"
