#!/bin/bash

echo "Kui vana te olete: "
read vanus

if test $vanus -gt 0 -a $vanus -lt 11
then
echo "Oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "oled teismeline"
elif test $vanus -ge 18 -a $vanus -lt 63
then 
echo "oled täiskasvanu"
elif test $vanus -ge 63 
then
echo "oled vana"
else
echo "vale sisend"
fi
