#!/bin/bash

echo -e "Sisesta kuu number \c"
read kuu

if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then
echo "praegu on Talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
echo "praegu on Suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then 
echo "Praegu on sügis"
else
echo "Aastas ei ole üle 12 kuu."
fi
