#!/bin/bash
#aja jargi tervitamine


var_1="$(logname)"
aeg=$(date +"%H")
#kontrollime
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo " Tere Hommikust, ${var_1}!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo " Tere Paevast, ${var_1}!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo " Tere õhtust, ${var_1} !"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo " Head ööd, ${var_1}!"
else
	echo "vale sisend"
fi
